Attribute VB_Name = "modExtentions"
Public Function GetFileExtention(ByRef EXTENTIONS As String)
If Left(EXTENTIONS, 1) <> "." Then
    If Mid(EXTENTIONS, 2, Len(EXTENTIONS)) = ".JS" Then
        EXTENTIONS = "JS"
        Exit Function
    End If
    If EXTENTIONS <> "HTML" Then
        If EXTENTIONS <> "MPEG" Then
            EXTENTIONS = "FILE"
            Exit Function
        End If
    End If
End If

Select Case EXTENTIONS
Case ".MDB"
    EXTENTIONS = "MDB"
Case ".ARX"
    EXTENTIONS = "ARX"
Case ".DWG"
    EXTENTIONS = "DWG"
Case ".XMX"
    EXTENTIONS = "XMX"
Case ".UDL"
    EXTENTIONS = "UDL"
Case ".HDI"
    EXTENTIONS = "HDI"
Case ".CTL"
    EXTENTIONS = "CTL"
Case ".CHM"
    EXTENTIONS = "CHM"
Case ".SCR"
    EXTENTIONS = "SCR"
Case ".MDZ"
    EXTENTIONS = "WAV"
Case ".MID"
    EXTENTIONS = "WAV"
Case ".WMF"
    EXTENTIONS = "BMP"
Case ".CLS"
    EXTENTIONS = "CLS"
Case ".XLA"
    EXTENTIONS = "XLA"
Case ".POT"
    EXTENTIONS = "POT"
Case ".DOT"
    EXTENTIONS = "DOT"
Case ".NFO"
    EXTENTIONS = "DOC"
Case ".PPA"
    EXTENTIONS = "PPA"
Case ".DIZ"
    EXTENTIONS = "DOC"
Case ".SEU"
    EXTENTIONS = "SEU"
Case ".HLP"
    EXTENTIONS = "HLP"
Case ".XML"
    EXTENTIONS = "XML"
Case "MPEG"
    EXTENTIONS = "ANI"
Case ".PDF"
    EXTENTIONS = "PDF"
Case ".LNK"
    EXTENTIONS = "SC"
Case ".FRM"
    EXTENTIONS = "FRM"
Case ".BAS"
    EXTENTIONS = "BAS"
Case ".VBP"
    EXTENTIONS = "VB"
Case ".PSP"
    EXTENTIONS = "BMP"
Case ".BMP"
    EXTENTIONS = "PNT"
Case ".JPG"
    EXTENTIONS = "BMP"
Case ".TGA"
    EXTENTIONS = "BMP"
Case ".GIF"
    EXTENTIONS = "BMP"
Case ".ANI"
    EXTENTIONS = "ANI"
Case ".WSZ"
    EXTENTIONS = "M3U"
Case ".M3U"
    EXTENTIONS = "M3U"
Case ".MPG"
    EXTENTIONS = "ANI"
Case ".AVI"
    EXTENTIONS = "ANI"
Case "MPEG"
    EXTENTIONS = "ANI"
Case ".DLL"
    EXTENTIONS = "DLL"
Case ".VXD"
    EXTENTIONS = "DLL"
Case ".386"
    EXTENTIONS = "DLL"
Case ".CPL"
    EXTENTIONS = "DLL"
Case ".DRV"
    EXTENTIONS = "DLL"
Case ".KEY"
    EXTENTIONS = "REG"
Case ".OCX"
    EXTENTIONS = "DLL"
Case ".CAT"
    EXTENTIONS = "CAT"
Case ".CRT"
    EXTENTIONS = "CRT"
Case ".HTM"
    EXTENTIONS = "IE"
Case "HTML"
    EXTENTIONS = "IE"
Case ".URL"
    EXTENTIONS = "URL"
Case ".RAR"
    EXTENTIONS = "RAR"
Case ".CAB"
    EXTENTIONS = "RAR"
Case ".LOG"
    EXTENTIONS = "RTF"
Case ".RTF"
    EXTENTIONS = "RTF"
Case ".DOC"
    EXTENTIONS = "DOC"
Case ".DAT"
    EXTENTIONS = "DOC"
Case ".INF"
    EXTENTIONS = "DOC"
Case ".SWF"
    EXTENTIONS = "SWF"
Case ".ASP"
    EXTENTIONS = "ASP"
Case ".TXT"
    EXTENTIONS = "TXT"
Case ".INI"
    EXTENTIONS = "INI"
Case ".INF"
    EXTENTIONS = "INI"
Case ".PPT"
    EXTENTIONS = "PPT"
Case ".XLS"
    EXTENTIONS = "XLS"
Case ".BAT"
    EXTENTIONS = "TXT"
Case ".SYS"
    EXTENTIONS = "TXT"
Case ".WAV"
    EXTENTIONS = "WAV"
Case ".MP3"
    EXTENTIONS = "WAV"
Case ".TMP"
    EXTENTIONS = "DOC"
Case ".ZIP"
    EXTENTIONS = "ZIP"
Case ".GID"
    EXTENTIONS = "GID"
Case ".EXE"
    EXTENTIONS = "EXE"
Case ".TTF"
    EXTENTIONS = "FNT"
Case ".SHX"
    EXTENTIONS = "FNT"
Case ".XFM"
    EXTENTIONS = "XFM"
Case ".FLT"
    EXTENTIONS = "XFM"
Case ".REG"
    EXTENTIONS = "REG"
Case ".HTT"
    EXTENTIONS = "HTT"
Case ".DBX"
    EXTENTIONS = "DBX"
End Select
If Len(EXTENTIONS) > 3 Then EXTENTIONS = "FILE"
End Function
